### PR TITLE
Simple fix to prevent sent headers

### PR DESCRIPTION
**Pull request by stevefan1999**

### CODE REVIEW

**Comment by alidcastano** [comment]
Were you running into conflicting header errors? 

Also, why do we need `res.headersSent` (without the `s`)? I was only able to find the one with the `s` https://nodejs.org/api/http.html#http_response_headerssent

**Comment by alidcastano** [comment]
What do you mean by "port"? like you're serving your rogue site from your backend?

also - talking about backends - I'll be releasing my own framework for that too in case you want to give it an early look https://github.com/alidcastano/druid.js :) pretty exicted about it

**Comment by stevefan1999** [comment]
Yeah, I leveraged the `introspectSchema` and `makeRemoteExecutableSchema` to stitch a 1-to-1 wrapper to my existing endpoint, but the only problem left is this weird HTTP header error and WebSocket problem. I don't know why the headers are sent, because it is shaded under an unknown async function, and I probably have to attach a debugger to fix it. Also if I enabled CORS, the same problem appears but this time it redirects to the `cors` instead. I was hoping if I use the internal `graphql-yoga` server would help at this. But anyway adding a simple guard wouldn't hurt isn't?

For why I have `headers?Sent`, it is due to the difference of Express 3 (singular, headerSent) and Express 4 (plural, headersSent) in the response object. I can drop it if you are sure that nobody is going to use Express 3 ever again.

**Comment by alidcastano** [comment]
Yea let's drop the second one since this is a new framework and I'll merge PR

**Comment by alidcastano** [comment]
Also lets add comment for why were adding this line for future reference

**Pull request merged**
